/**
 * POST /api/projects/[id]/export — produces a single bundle of all artifacts.
 *
 * Query: ?format=md (default) | docx
 * Body: { project: ProjectRecord }
 */
import type { NextRequest } from "next/server";
import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";

export const runtime = "nodejs";

interface ExportBody {
  project: {
    title?: string;
    premise?: Record<string, unknown>;
    setting?: Record<string, unknown>;
    characters?: Array<Record<string, unknown>>;
    story?: Record<string, unknown>;
    manuscript?: {
      chunks: Array<{ index: number; title: string; prose: string }>;
      totalWords?: number;
      totalCost?: number;
      completedAt?: string;
    };
  };
}

export async function POST(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  const body = (await req.json()) as ExportBody;
  const p = body.project ?? {};
  const url = new URL(req.url);
  const format = url.searchParams.get("format") ?? "md";
  const safeName = (p.title ?? "novelwright").replace(/[^a-z0-9]+/gi, "_");

  if (format === "docx") {
    const buffer = await renderDocx(p);
    // Buffer is a Uint8Array subclass but TS Response BodyInit prefers explicit Uint8Array
    const bytes = new Uint8Array(buffer);
    return new Response(bytes, {
      headers: {
        "content-type":
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "content-disposition": `attachment; filename="${safeName}.docx"`,
      },
    });
  }

  // Default: markdown
  const md = renderMarkdown(p, id);
  return new Response(md, {
    headers: {
      "content-type": "text/markdown; charset=utf-8",
      "content-disposition": `attachment; filename="${safeName}.md"`,
    },
  });
}

/**
 * Build a manuscript-style .docx — title page + chapters + body prose.
 * Skips planning artifacts; this is the "literary deliverable" format.
 */
async function renderDocx(p: ExportBody["project"]): Promise<Buffer> {
  const title = p.title ?? "Untitled";
  const children: Paragraph[] = [];

  // Title page
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 2400, after: 240 },
      children: [
        new TextRun({
          text: title,
          bold: true,
          size: 48,
          font: "Georgia",
        }),
      ],
    }),
  );
  if (p.premise && (p.premise as Record<string, string>).hook) {
    children.push(
      new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { after: 480 },
        children: [
          new TextRun({
            text: (p.premise as Record<string, string>).hook,
            italics: true,
            size: 22,
            font: "Georgia",
          }),
        ],
      }),
    );
  }
  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 600 },
      children: [
        new TextRun({
          text: "Generated by NovelWright",
          size: 18,
          color: "888888",
          font: "Calibri",
        }),
      ],
    }),
  );

  // Chunks → Chapters
  const chunks = p.manuscript?.chunks ?? [];
  for (const c of chunks) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        pageBreakBefore: true,
        spacing: { before: 480, after: 360 },
        children: [
          new TextRun({
            text: c.title,
            bold: true,
            size: 32,
            font: "Georgia",
          }),
        ],
      }),
    );
    // Body — split prose by blank lines into paragraphs
    const paras = (c.prose ?? "").split(/\n\s*\n/).filter((s) => s.trim());
    for (const para of paras) {
      children.push(
        new Paragraph({
          spacing: { after: 200, line: 360 }, // 1.5x line height
          children: [
            new TextRun({
              text: para.replace(/\n/g, " "),
              size: 24, // 12pt
              font: "Georgia",
            }),
          ],
        }),
      );
    }
  }

  const doc = new Document({
    creator: "NovelWright",
    title,
    description: "AI-co-authored manuscript",
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440, // 1 inch
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        children,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}

function renderMarkdown(p: ExportBody["project"], id: string): string {
  const parts: string[] = [];

  parts.push(`# ${p.title ?? "Untitled"}\n`);
  parts.push(`*Generated by NovelWright · ${new Date().toISOString()} · project ${id}*\n\n---\n`);

  if (p.premise) {
    parts.push(`## Premise\n`);
    const premise = p.premise as Record<string, string>;
    if (premise.hook) parts.push(`**Hook:** ${premise.hook}\n`);
    if (premise.coreDesire) parts.push(`**Core Desire:** ${premise.coreDesire}\n`);
    if (premise.conflictDriver) parts.push(`**Conflict Driver:** ${premise.conflictDriver}\n`);
    if (premise.structuralLayer) parts.push(`**Structural Layer:** ${premise.structuralLayer}\n`);
    if (premise.protagonistPositioning)
      parts.push(`**Protagonist Positioning:** ${premise.protagonistPositioning}\n`);
    if (premise.climaxShape) parts.push(`**Climax Shape:** ${premise.climaxShape}\n`);
    if (premise.derivationChainTrace) parts.push(`\n${premise.derivationChainTrace}\n`);
    parts.push("\n---\n");
  }

  if (p.setting) {
    parts.push(`## Setting\n`);
    const setting = p.setting as Record<string, unknown>;
    const voice = setting.narrativeVoice as Record<string, unknown> | undefined;
    if (voice) {
      parts.push(`### Narrative Voice\n`);
      if (voice.narrator) parts.push(`- **Narrator:** ${voice.narrator}\n`);
      if (voice.languageStyle) parts.push(`- **Language Style:** ${voice.languageStyle}\n`);
      if (Array.isArray(voice.allowedLensModes))
        parts.push(`- **Allowed Lens Modes:** ${(voice.allowedLensModes as string[]).join(", ")}\n`);
      parts.push("\n");
    }
    const rules = setting.worldRules as Array<Record<string, string>> | undefined;
    if (rules && rules.length > 0) {
      parts.push(`### World Rules\n\n| # | Rule | Serves | Loss if removed |\n| - | ---- | ------ | --------------- |\n`);
      for (let i = 0; i < rules.length; i++) {
        const r = rules[i]!;
        parts.push(
          `| ${i + 1} | ${r.rule ?? ""} | ${r.serves ?? ""} | ${r.lossIfRemoved ?? ""} |\n`,
        );
      }
      parts.push("\n");
    }
    parts.push("---\n");
  }

  if (p.characters && p.characters.length > 0) {
    parts.push(`## Characters\n`);
    for (const c of p.characters) {
      parts.push(`### ${c.name ?? "(Unnamed)"} — ${c.role ?? "(no role)"}\n\n`);
      const cdr = c.desirePositioning as Record<string, string> | undefined;
      if (cdr) {
        if (cdr.coreDesire) parts.push(`**Core Desire:** ${cdr.coreDesire}\n\n`);
        if (cdr.irreplaceability) parts.push(`**Irreplaceability:** ${cdr.irreplaceability}\n\n`);
      }
      const cap = c.appearance as Record<string, unknown> | undefined;
      if (cap) {
        parts.push(`**Appearance**\n`);
        if (cap.face) parts.push(`- Face: ${cap.face}\n`);
        if (cap.build) parts.push(`- Build: ${cap.build}\n`);
        if (cap.aura) parts.push(`- Aura: ${cap.aura}\n`);
        if (cap.distinctiveness != null) parts.push(`- Distinctiveness: ${cap.distinctiveness}/10\n`);
        parts.push("\n");
      }
      const cper = c.personality as Record<string, string> | undefined;
      if (cper) {
        parts.push(`**Personality**\n`);
        if (cper.surface) parts.push(`- Surface: ${cper.surface}\n`);
        if (cper.interior) parts.push(`- Interior: ${cper.interior}\n`);
        if (cper.gap) parts.push(`- Gap: ${cper.gap}\n`);
        parts.push("\n");
      }
      const anchors = c.anchorBehaviors as Array<Record<string, string>> | undefined;
      if (anchors && anchors.length > 0) {
        parts.push(`**Anchor Behaviors**\n\n| Anchor | Phase 1 | Phase 3 | Phase 5 |\n| ------ | ------- | ------- | ------- |\n`);
        for (const a of anchors) {
          parts.push(`| ${a.name ?? ""} | ${a.phase1 ?? ""} | ${a.phase3 ?? ""} | ${a.phase5 ?? ""} |\n`);
        }
        parts.push("\n");
      }
      const v = c.voiceDNA as Record<string, string> | undefined;
      if (v) {
        parts.push(`**Voice DNA**\n`);
        if (v.rhythm) parts.push(`- Rhythm: ${v.rhythm}\n`);
        if (v.vocabulary) parts.push(`- Vocabulary: ${v.vocabulary}\n`);
        if (v.signaturePattern) parts.push(`- Signature: ${v.signaturePattern}\n`);
        parts.push("\n");
      }
    }
    parts.push("---\n");
  }

  if (p.story) {
    parts.push(`## Plot Structure\n`);
    const story = p.story as Record<string, unknown>;
    const spine = story.spine as Record<string, string> | undefined;
    if (spine) {
      if (spine.corePremise) parts.push(`**Core Premise:** ${spine.corePremise}\n\n`);
      if (spine.arcShape) parts.push(`**Arc Shape:** ${spine.arcShape}\n\n`);
      if (spine.timeline) parts.push(`**Timeline:** ${spine.timeline}\n\n`);
    }
    const chunks = story.chunks as Array<Record<string, unknown>> | undefined;
    if (chunks && chunks.length > 0) {
      for (const c of chunks) {
        parts.push(`### Chunk ${c.index ?? "?"}: ${c.title ?? "Untitled"}\n\n`);
        if (c.timeline) parts.push(`**Timeline:** ${c.timeline}\n\n`);
        if (c.intensityTier != null) parts.push(`**Intensity Tier:** ${c.intensityTier}\n\n`);
        if (c.focus) parts.push(`**Focus:** ${c.focus}\n\n`);
        if (c.stateFlow) parts.push(`**State Flow:**\n\n${c.stateFlow}\n\n`);
        const beats = c.beats as Array<Record<string, unknown>> | undefined;
        if (beats && beats.length > 0) {
          parts.push(`**Beats:**\n\n| # | Content | Dilation | Focus |\n| - | ------- | -------- | ----- |\n`);
          for (const b of beats) {
            parts.push(
              `| ${b.number ?? ""} | ${b.content ?? ""} | ${b.dilation ?? ""} | ${b.focus ?? ""} |\n`,
            );
          }
          parts.push("\n");
        }
      }
    }
    parts.push("---\n");
  }

  if (p.manuscript) {
    parts.push(`## Manuscript\n`);
    parts.push(
      `*${p.manuscript.totalWords ?? "?"} words · completed ${
        p.manuscript.completedAt ?? "?"
      }*\n\n`,
    );
    for (const c of p.manuscript.chunks ?? []) {
      parts.push(`### ${c.title}\n\n`);
      parts.push(c.prose);
      parts.push("\n\n");
    }
  }

  return parts.join("");
}
